services:
  - type: web
    name: receitas-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan migrate:fresh --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
